# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests or author to add the pr author
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub username)
reviewers:
# ⚙️  Add the usernames of the developers working in the project
  - USERNAME_1
  - USERNAME_2

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
