name: 'Pull request automation'
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    name: Add reviewers
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/pr-assigner.yml'

  add-labeler:
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    name: Add labels
    steps:
      - uses: TimonVS/pr-labeler-action@v3.1.0
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-test:
    name: Test & coverage
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install Go
        uses: actions/setup-go@v3.1.0
        with:
          go-version: 1.18.x

      - name: Calc coverage
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out

      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        
      - name: Post Coverage Report
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: './coverage.lcov'
          lcov-base: './coverage/lcov.info'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          delete-old-comments: true
          title: ':open_umbrella: Code Coverage'
