name: 'Pull request automation'
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    name: Add reviewers
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: '.github/pr-assigner.yml'
  add-labeler:
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    name: Add labels
    steps:
      - uses: TimonVS/pr-labeler-action@v3.1.0
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'GigapipeBot'
    env:
    # ⚙️  Add the necessary env variables to execute the tests
      YOUR_ENV: 'SOMETHING'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up Python 3.10.2
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[testing]

      - name: Running Pytests
        run: |
          pytest -rA app/tests